import random

weapontable = [
    "Bandit Axe",
    "Battle Axe",
    "Bound Hand Axe",
    "Butcher's Knife",
    "Dragonslayer's Crescent Axe",
    "Gyrm Axe",
    "Hand Axe",
    "Infantry Axe",
    "Bell Keeper Bow",
    "Bow of Want",
    "Composite Bow",
    "Dragonrider Bow",
    "Hunter's Blackbow",
    "Long Bow",
    "Sea Bow",
    "Short Bow",
    "Claws",
    "Malformed Claws",
    "Manikin Claws",
    "Work Hook",
    "Avelyn",
    "Heavy Crossbow",
    "Light Crossbow",
    "Sanctum Crossbow",
    "Sanctum Repeating Crossbow",
    "Shield Crossbow",
    "Eleum Loyce",
    "Falchion",
    "Manikin Sabre",
    "Melu Scimitar",
    "Monastery Scimitar",
    "Red Rust Scimitar",
    "Scimitar",
    "Shotel",
    "Spider Fang",
    "Warped Sword",
    "Arced Sword",
    "Curved Dragon Greatsword",
    "Curved Nil Greatsword",
    "Murakumo",
    "Bandit's Knife",
    "Black Flamestone Dagger",
    "Blue Dagger",
    "Broken Thief Sword",
    "Dagger",
    "Manikin Knife",
    "Mytha's Bent Blade",
    "Parrying Dagger",
    "Retainer's Short Sword",
    "Royal Dirk",
    "Shadow Dagger",
    "Thief Dagger",
    "Umbral Dagger",
    "Bone Fist",
    "Caestus",
    "Fists",
    "Fists (Vanquisher's Seal)",
    "Bandit Greataxe",
    "Black Dragon Greataxe",
    "Black Knight Greataxe",
    "Crescent Axe",
    "Drakekeeper's Greataxe",
    "Greataxe",
    "Giant Stone Axe",
    "Gyrm Greataxe",
    "Lion Greataxe",
    "Alonne Greatbow",
    "Dragonslayer Greatbow",
    "Possessed Armor Greatbow",
    "Twin-headed Greatbow",
    "Archdrake Mace",
    "Demon's Great Hammer",
    "Dragon Tooth",
    "Drakekeeper's Great Hammer",
    "Drakekeeper's Warpick",
    "Giant Warrior Club",
    "Great Club",
    "Gyrm Great Hammer",
    "Iron King Hammer",
    "Large Club",
    "Malformed Shell",
    "Malformed Skull",
    "Old Knight Hammer",
    "Pickaxe",
    "Sacred Chime Hammer",
    "Sanctum Mace",
    "Smelter Hammer",
    "Bastard Sword",
    "Black Dragon Greatsword",
    "Black Knight Greatsword",
    "Bluemoon Greatsword",
    "Charred Loyce Greatsword",
    "Claymore",
    "Defender Greatsword",
    "Drakeblood Greatsword",
    "Drangleic Sword",
    "Flamberge",
    "Greatsword of the Forlorn",
    "Key to the Embedded",
    "Loyce Greatsword",
    "Majestic Greatsword (Right hand)",
    "Majestic Greatsword (Left hand)",
    "Mastodon Greatsword",
    "Mirrah Greatsword",
    "Moonlight Greatsword",
    "Old Knight Greatsword",
    "Old Mirrah Greatsword",
    "Royal Greatsword",
    "Ruler's Sword",
    "Thorned Greatsword",
    "Watcher Greatsword",
    "Black Knight Halberd",
    "Blue Knight's Halberd",
    "Dragonrider's Halberd",
    "Halberd",
    "Helix Halberd",
    "Lucerne",
    "Mastodon Halberd",
    "Old Knight Halberd",
    "Old Knight Pike",
    "Roaring Halberd",
    "Santier's Spear (Unbroken)",
    "Santier's Spear (Broken)",
    "Scythe",
    "Syan's Halberd",
    "Wrathful Axe",
    "Aldia Hammer",
    "Barbed Club",
    "Blacksmith's Hammer",
    "Black Dragon Warpick",
    "Club",
    "Craftsman's Hammer",
    "Handmaid's Ladle",
    "Homunculus Mace",
    "Mace",
    "Mace of the Insolent",
    "Morning Star",
    "Reinforced Club",
    "Berserker Blade",
    "Bewitched Alonne Sword",
    "Blacksteel Katana",
    "Chaos Blade",
    "Darkdrift",
    "Manslayer",
    "Uchigatana",
    "Washing Pole",
    "Chariot Lance",
    "Grand Lance",
    "Heide Greatlance",
    "Heid Lance",
    "Rampart Golem Lance",
    "Bone Scythe",
    "Crescent Sickle",
    "Full Moon Sickle",
    "Great Machete",
    "Great Scythe",
    "Scythe of the Forlorn",
    "Scythe of Nahr Alma",
    "Scythe of Want",
    "Silverblack Sickle",
    "Channeler's Trident",
    "Dragonslayer Spear",
    "Gargoyle Bident",
    "Heide Spear",
    "Partizan",
    "Pate's Spear",
    "Pike",
    "Pilgrim's Spontoon",
    "Silverblack Spear",
    "Spear",
    "Spitfire Spear",
    "Stone Soldier Spear",
    "Winged Spear",
    "Yorgh's Spear",
    "Ashen Warrior Sword",
    "Black Dragon Sword",
    "Blue Flame",
    "Broadsword",
    "Broken Straight Sword",
    "Drakekeeper's Sword",
    "Foot Soldier Sword",
    "Fume Sword",
    "Heide Knight Sword",
    "Ivory Straight Sword",
    "Longsword",
    "Possessed Armor Sword",
    "Puzzling Stone Sword",
    "Red Rust Sword",
    "Shortsword",
    "Sun Sword",
    "Varangian Sword",
    "Yellow Quartz Longsword",
    "Black Scorpion Stinger",
    "Chaos Rapier",
    "Espada Ropera",
    "Estoc",
    "Ice Rapier",
    "Mail Breaker",
    "Rapier",
    "Ricard's Rapier",
    "Spider's Silk",
    "Curved Twinblade",
    "Dragonrider Twinblade",
    "Red Iron Twinblade",
    "Sorcerer's Twinblade",
    "Twinblade",
    "Aged Smelter Sword",
    "Black Knight Ultra Greatsword",
    "Crypt Blacksword",
    "Drakekeeper's Ultra Greatsword",
    "Drakewing Ultra Greatsword",
    "Fume Ultra Greatsword",
    "Greatsword",
    "Ivory King Ultra Greatsword",
    "King's Ultra Greatsword",
    "Lost Sinner's Sword",
    "Old Knight Ultra Greatsword",
    "Pursuer's Ultra Greatsword",
    "Smelter Sword",
    "Zweihander",
    "Bloodied Whip",
    "Notched Whip",
    "Old Whip",
    "Old Whip (on hollows)",
    "Spotted Whip",
    "Whip"]



print(weapontable[random.randrange(0, len(weapontable))])